In [1]:
import tensorflow as tf

In [2]:
import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()

Instructions for updating:
Use the retry module or similar alternatives.


In [3]:
a=tf.constant([[2,3],[4,5]],shape=[2,2],verify_shape=True)

In [4]:
type(a)

EagerTensor

In [5]:
#Mathematical Operations (No need of session)
# Code will run pythonically Imperatively
mul=tf.multiply(a,a)
print(mul)

tf.Tensor(
[[ 4  9]
 [16 25]], shape=(2, 2), dtype=int32)


In [6]:
add=tf.add(a,a)
print(add)

tf.Tensor(
[[ 4  6]
 [ 8 10]], shape=(2, 2), dtype=int32)


In [7]:
sub=tf.subtract(a,a)
print(sub)

tf.Tensor(
[[0 0]
 [0 0]], shape=(2, 2), dtype=int32)


In [ ]:
# After you can do any operations with eager execution like above